"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "pt" | "es" | "en" | "fr" | "it" | "ja" | "ru" | "de";

interface Translations {
  [key: string]: {
    [key: string]: string | { [key: string]: string };
  };
}

const translations: Translations = {
  pt: {
    // Navbar
    nav: {
      dashboard: "Dashboard",
      forecast: "Previsão",
      history: "Histórico",
      replay: "Replay",
      contacts: "Contatos",
    },
    // Header
    header: {
      title: "Monitor de Tempestades de Granizo",
      subtitle: "Monitoramento em tempo real de eventos climáticos severos",
    },
    // Database
    database: {
      title: "Banco de Dados Histórico Completo",
      badge: "10+ Anos",
      description:
        "Acesse mais de uma década de dados históricos de granizo com mapas detalhados e análises",
      years: "10+ anos de dados",
      countries: "50+ países",
      realtime: "Atualização em tempo real",
    },
    // Alert
    alert: {
      title: "Alerta de Tempestade Severa Ativa",
      description:
        "Múltiplas áreas sob alerta de granizo severo. Monitoramento ativo em 12 regiões.",
    },
    // Cards
    cards: {
      temperature: "Temperatura",
      precipitation: "Precipitação",
      windSpeed: "Velocidade do Vento",
      humidity: "Umidade",
    },
    // Monitoring
    monitoring: {
      title: "Áreas de Monitoramento",
      areas: "áreas monitoradas",
      inUS: "nos Estados Unidos",
      filter: "Filtrar por país",
      allCountries: "Todos os Países",
      highRisk: "Alto Risco",
      mediumRisk: "Risco Médio",
      lowRisk: "Baixo Risco",
      updatedAgo: "Atualizado há",
      hailProbability: "Probabilidade de Granizo",
      expectedSize: "Tamanho Esperado",
      temp: "Temp",
      wind: "Vento",
      noAreas: "Nenhuma área encontrada para este filtro",
    },
    // Charts
    charts: {
      temperature24h: "Temperatura (24h)",
      forecastToday: "Previsão para hoje",
      precipitation7d: "Precipitação (7 dias)",
      weeklyHistory: "Histórico semanal",
    },
    // Activity
    activity: {
      title: "Atividade Recente",
      events: {
        severeHail: "Granizo severo detectado",
        tornadoAlert: "Alerta de tornado emitido",
        severeStorm: "Tempestade severa em andamento",
        favorableConditions: "Condições favoráveis para granizo",
        monitoringStarted: "Monitoramento iniciado",
      },
    },
    // Time
    time: {
      minutesAgo: "há {0} minutos",
    },
    // Forecast
    forecast: {
      title: "Previsão de Granizo - Próximos 12 Meses",
      subtitle: "Mapas preditivos e análise de risco para os próximos 12 meses",
      highRisk: "Alto Risco",
      mediumRisk: "Risco Médio",
      lowRisk: "Baixo Risco",
      predictedEvents: "eventos previstos",
      events: "eventos",
      riskDescription:
        "Período de alta atividade previsto com múltiplos eventos severos",
      peakDays: "Dias de Pico",
      avgEvents: "Eventos Médios",
      perMonth: "por mês",
      affectedRegions: "Regiões Afetadas",
      mainRegions: "principais regiões",
      peakDaysCount: "Dias de Pico",
      highRiskDays: "dias de alto risco",
      riskLevel: "Nível de Risco",
      forMonth: "para o mês",
    },
    // History
    history: {
      title: "Histórico de Granizo - 10+ Anos",
      subtitle: "Banco de dados completo com mais de uma década de eventos",
      allRegions: "Todas as Regiões",
      searchPlaceholder: "Buscar por localização, data ou evento...",
      export: "Exportar",
      totalEvents: "Total de Eventos",
      severe: "severos",
      affectedStates: "Estados Afetados",
      acrossUS: "nos EUA",
      totalDamage: "Danos Totais",
      estimated: "estimado",
      peakMonth: "Mês de Pico",
      mostActive: "mais ativo",
      avgHailSize: "Tamanho Médio",
      diameter: "diâmetro",
      dataPoints: "Pontos de Dados",
      collected: "coletados",
      notableEvents: "Eventos Notáveis",
      hailSize: "Tamanho do Granizo",
      estimatedDamage: "danos estimados",
    },
    // Replay
    replay: {
      title: "Hail Replay™ - Reprodução de Radar",
      subtitle: "Reviva eventos históricos com imagens de radar em alta definição",
      selectEvent: "Selecionar Evento",
      radarView: "Visualização de Radar",
      timestamp: "Horário",
      maxHailSize: "Tamanho Máx. Granizo",
      speed: "Velocidade",
      eventDetails: "Detalhes do Evento",
      date: "Data",
      timeRange: "Horário",
      location: "Localização",
      severity: "Severidade",
      statistics: "Estatísticas",
      duration: "Duração",
      frames: "Frames",
      maxHail: "Granizo Máx.",
      damage: "Danos",
      download: "Baixar Replay",
      share: "Compartilhar",
    },
    // Contacts
    contacts: {
      title: "Dados de Contato Ilimitados",
      subtitle: "Acesso sob demanda a milhares de contatos qualificados",
      addNew: "Adicionar Novo",
      import: "Importar",
      totalContacts: "Total de Contatos",
      unlimited: "ilimitado",
      companies: "Empresas",
      business: "empresariais",
      locations: "Localizações",
      states: "estados",
      categories: "Categorias",
      types: "tipos",
      searchPlaceholder: "Buscar por nome, email ou telefone...",
      export: "Exportar Lista",
      name: "Nome",
      contact: "Contato",
      location: "Localização",
      category: "Categoria",
      lastContact: "Último Contato",
      noResults: "Nenhum contato encontrado",
      allCategories: "Todas as Categorias",
      homeowners: "Proprietários",
      contractors: "Empreiteiros",
      insurance: "Seguradoras",
      roofing: "Telhados",
      restoration: "Restauração",
    },
    // Months
    months: {
      january: "Janeiro",
      february: "Fevereiro",
      march: "Março",
      april: "Abril",
      may: "Maio",
      june: "Junho",
      july: "Julho",
      august: "Agosto",
      september: "Setembro",
      october: "Outubro",
      november: "Novembro",
      december: "Dezembro",
    },
    // Disclaimer
    disclaimer: {
      title: "Aviso Legal e Isenção de Responsabilidade",
      lastUpdated: "Última atualização: Janeiro 2025",
      backToHome: "Voltar ao Início",
      importantNotice: "Aviso Importante",
      importantText: "Por favor, leia este aviso legal cuidadosamente antes de usar o Hai Watch. Ao acessar e usar este aplicativo, você concorda com os termos e condições aqui estabelecidos.",
      section1: {
        title: "1. Isenção Geral",
        p1: "O Hai Watch é uma ferramenta de monitoramento meteorológico fornecida 'como está' e 'conforme disponível'. As informações apresentadas neste aplicativo são apenas para fins informativos e educacionais.",
        p2: "Este aplicativo NÃO substitui alertas meteorológicos oficiais emitidos por autoridades governamentais competentes (como NOAA, NWS, INMET, ou equivalentes locais).",
        p3: "O criador e desenvolvedor deste aplicativo não se responsabiliza por quaisquer decisões tomadas com base nas informações fornecidas.",
      },
      section2: {
        title: "2. Precisão dos Dados",
        p1: "Embora nos esforcemos para fornecer informações precisas e atualizadas, não garantimos a exatidão, completude, confiabilidade ou adequação das informações meteorológicas apresentadas.",
        p2: "Os dados podem conter erros, imprecisões ou estar desatualizados. Condições meteorológicas podem mudar rapidamente e sem aviso prévio.",
      },
      section3: {
        title: "3. Limitação de Responsabilidade",
        p1: "Em nenhuma circunstância o criador, desenvolvedor ou qualquer parte afiliada será responsável por quaisquer danos diretos, indiretos, incidentais, especiais, consequenciais ou punitivos resultantes do uso ou incapacidade de usar este aplicativo.",
        p2: "Isso inclui, mas não se limita a: danos materiais, perdas financeiras, lesões pessoais, perda de dados ou lucros cessantes.",
      },
      section4: {
        title: "4. Responsabilidades do Usuário",
        intro: "Ao usar o Hai Watch, você concorda em:",
        item1: "Consultar sempre fontes oficiais de meteorologia para decisões críticas de segurança",
        item2: "Não confiar exclusivamente neste aplicativo para proteção de vida ou propriedade",
        item3: "Verificar informações com múltiplas fontes confiáveis",
        item4: "Seguir todas as orientações de segurança emitidas por autoridades locais",
      },
      section5: {
        title: "5. Não Constitui Aconselhamento Profissional",
        p1: "As informações fornecidas não constituem aconselhamento profissional meteorológico, legal, financeiro ou de qualquer outra natureza. Para decisões importantes, consulte profissionais qualificados.",
      },
      section6: {
        title: "6. Dados de Terceiros",
        p1: "Este aplicativo pode utilizar dados de fontes de terceiros. Não controlamos nem garantimos a precisão dessas fontes externas e não nos responsabilizamos por erros ou omissões em dados de terceiros.",
      },
      section7: {
        title: "7. Alterações no Aviso Legal",
        p1: "Reservamo-nos o direito de modificar este aviso legal a qualquer momento. Alterações entram em vigor imediatamente após publicação. O uso continuado do aplicativo após alterações constitui aceitação dos novos termos.",
      },
      section8: {
        title: "8. Lei Aplicável",
        p1: "Este aviso legal é regido pelas leis aplicáveis da jurisdição onde o criador reside, sem considerar conflitos de disposições legais.",
      },
      contact: {
        title: "Dúvidas sobre este Aviso Legal?",
        text: "Se você tiver dúvidas sobre este aviso legal, entre em contato através dos canais oficiais do aplicativo.",
      },
    },
  },
  es: {
    // Navbar
    nav: {
      dashboard: "Panel",
      forecast: "Pronóstico",
      history: "Historial",
      replay: "Repetición",
      contacts: "Contactos",
    },
    // Header
    header: {
      title: "Monitor de Tormentas de Granizo",
      subtitle: "Monitoreo en tiempo real de eventos climáticos severos",
    },
    // Database
    database: {
      title: "Base de Datos Histórica Completa",
      badge: "10+ Años",
      description:
        "Acceda a más de una década de datos históricos de granizo con mapas detallados y análisis",
      years: "10+ años de datos",
      countries: "50+ países",
      realtime: "Actualización en tiempo real",
    },
    // Alert
    alert: {
      title: "Alerta de Tormenta Severa Activa",
      description:
        "Múltiples áreas bajo alerta de granizo severo. Monitoreo activo en 12 regiones.",
    },
    // Cards
    cards: {
      temperature: "Temperatura",
      precipitation: "Precipitación",
      windSpeed: "Velocidad del Viento",
      humidity: "Humedad",
    },
    // Monitoring
    monitoring: {
      title: "Áreas de Monitoreo",
      areas: "áreas monitoreadas",
      inUS: "en Estados Unidos",
      filter: "Filtrar por país",
      allCountries: "Todos los Países",
      highRisk: "Alto Riesgo",
      mediumRisk: "Riesgo Medio",
      lowRisk: "Bajo Riesgo",
      updatedAgo: "Actualizado hace",
      hailProbability: "Probabilidad de Granizo",
      expectedSize: "Tamaño Esperado",
      temp: "Temp",
      wind: "Viento",
      noAreas: "No se encontraron áreas para este filtro",
    },
    // Charts
    charts: {
      temperature24h: "Temperatura (24h)",
      forecastToday: "Pronóstico para hoy",
      precipitation7d: "Precipitación (7 días)",
      weeklyHistory: "Historial semanal",
    },
    // Activity
    activity: {
      title: "Actividad Reciente",
      events: {
        severeHail: "Granizo severo detectado",
        tornadoAlert: "Alerta de tornado emitida",
        severeStorm: "Tormenta severa en curso",
        favorableConditions: "Condiciones favorables para granizo",
        monitoringStarted: "Monitoreo iniciado",
      },
    },
    // Time
    time: {
      minutesAgo: "hace {0} minutos",
    },
    // Forecast
    forecast: {
      title: "Pronóstico de Granizo - Próximos 12 Meses",
      subtitle: "Mapas predictivos y análisis de riesgo para los próximos 12 meses",
      highRisk: "Alto Riesgo",
      mediumRisk: "Riesgo Medio",
      lowRisk: "Bajo Riesgo",
      predictedEvents: "eventos previstos",
      events: "eventos",
      riskDescription:
        "Período de alta actividad previsto con múltiples eventos severos",
      peakDays: "Días Pico",
      avgEvents: "Eventos Promedio",
      perMonth: "por mes",
      affectedRegions: "Regiones Afectadas",
      mainRegions: "regiones principales",
      peakDaysCount: "Días Pico",
      highRiskDays: "días de alto riesgo",
      riskLevel: "Nivel de Riesgo",
      forMonth: "para el mes",
    },
    // History
    history: {
      title: "Historial de Granizo - 10+ Años",
      subtitle: "Base de datos completa con más de una década de eventos",
      allRegions: "Todas las Regiones",
      searchPlaceholder: "Buscar por ubicación, fecha o evento...",
      export: "Exportar",
      totalEvents: "Total de Eventos",
      severe: "severos",
      affectedStates: "Estados Afectados",
      acrossUS: "en EE.UU.",
      totalDamage: "Daños Totales",
      estimated: "estimado",
      peakMonth: "Mes Pico",
      mostActive: "más activo",
      avgHailSize: "Tamaño Promedio",
      diameter: "diámetro",
      dataPoints: "Puntos de Datos",
      collected: "recopilados",
      notableEvents: "Eventos Notables",
      hailSize: "Tamaño del Granizo",
      estimatedDamage: "daños estimados",
    },
    // Replay
    replay: {
      title: "Hail Replay™ - Reproducción de Radar",
      subtitle: "Reviva eventos históricos con imágenes de radar en alta definición",
      selectEvent: "Seleccionar Evento",
      radarView: "Vista de Radar",
      timestamp: "Hora",
      maxHailSize: "Tamaño Máx. Granizo",
      speed: "Velocidad",
      eventDetails: "Detalles del Evento",
      date: "Fecha",
      timeRange: "Horario",
      location: "Ubicación",
      severity: "Severidad",
      statistics: "Estadísticas",
      duration: "Duración",
      frames: "Cuadros",
      maxHail: "Granizo Máx.",
      damage: "Daños",
      download: "Descargar Repetición",
      share: "Compartir",
    },
    // Contacts
    contacts: {
      title: "Datos de Contacto Ilimitados",
      subtitle: "Acceso bajo demanda a miles de contactos calificados",
      addNew: "Agregar Nuevo",
      import: "Importar",
      totalContacts: "Total de Contactos",
      unlimited: "ilimitado",
      companies: "Empresas",
      business: "empresariales",
      locations: "Ubicaciones",
      states: "estados",
      categories: "Categorías",
      types: "tipos",
      searchPlaceholder: "Buscar por nombre, email o teléfono...",
      export: "Exportar Lista",
      name: "Nombre",
      contact: "Contacto",
      location: "Ubicación",
      category: "Categoría",
      lastContact: "Último Contacto",
      noResults: "No se encontraron contactos",
      allCategories: "Todas las Categorías",
      homeowners: "Propietarios",
      contractors: "Contratistas",
      insurance: "Aseguradoras",
      roofing: "Techos",
      restoration: "Restauración",
    },
    // Months
    months: {
      january: "Enero",
      february: "Febrero",
      march: "Marzo",
      april: "Abril",
      may: "Mayo",
      june: "Junio",
      july: "Julio",
      august: "Agosto",
      september: "Septiembre",
      october: "Octubre",
      november: "Noviembre",
      december: "Diciembre",
    },
    // Disclaimer
    disclaimer: {
      title: "Aviso Legal y Exención de Responsabilidad",
      lastUpdated: "Última actualización: Enero 2025",
      backToHome: "Volver al Inicio",
      importantNotice: "Aviso Importante",
      importantText: "Por favor, lea este aviso legal cuidadosamente antes de usar Hai Watch. Al acceder y usar esta aplicación, acepta los términos y condiciones aquí establecidos.",
      section1: {
        title: "1. Exención General",
        p1: "Hai Watch es una herramienta de monitoreo meteorológico proporcionada 'tal cual' y 'según disponibilidad'. La información presentada en esta aplicación es solo con fines informativos y educativos.",
        p2: "Esta aplicación NO reemplaza las alertas meteorológicas oficiales emitidas por autoridades gubernamentales competentes (como NOAA, NWS, AEMET, o equivalentes locales).",
        p3: "El creador y desarrollador de esta aplicación no se responsabiliza por cualquier decisión tomada basándose en la información proporcionada.",
      },
      section2: {
        title: "2. Precisión de los Datos",
        p1: "Aunque nos esforzamos por proporcionar información precisa y actualizada, no garantizamos la exactitud, integridad, confiabilidad o idoneidad de la información meteorológica presentada.",
        p2: "Los datos pueden contener errores, imprecisiones o estar desactualizados. Las condiciones meteorológicas pueden cambiar rápidamente y sin previo aviso.",
      },
      section3: {
        title: "3. Limitación de Responsabilidad",
        p1: "Bajo ninguna circunstancia el creador, desarrollador o cualquier parte afiliada será responsable de cualquier daño directo, indirecto, incidental, especial, consecuente o punitivo resultante del uso o incapacidad de usar esta aplicación.",
        p2: "Esto incluye, pero no se limita a: daños materiales, pérdidas financieras, lesiones personales, pérdida de datos o lucro cesante.",
      },
      section4: {
        title: "4. Responsabilidades del Usuario",
        intro: "Al usar Hai Watch, usted acepta:",
        item1: "Consultar siempre fuentes oficiales de meteorología para decisiones críticas de seguridad",
        item2: "No confiar exclusivamente en esta aplicación para protección de vida o propiedad",
        item3: "Verificar información con múltiples fuentes confiables",
        item4: "Seguir todas las orientaciones de seguridad emitidas por autoridades locales",
      },
      section5: {
        title: "5. No Constituye Asesoramiento Profesional",
        p1: "La información proporcionada no constituye asesoramiento profesional meteorológico, legal, financiero o de cualquier otra naturaleza. Para decisiones importantes, consulte profesionales calificados.",
      },
      section6: {
        title: "6. Datos de Terceros",
        p1: "Esta aplicación puede utilizar datos de fuentes de terceros. No controlamos ni garantizamos la precisión de estas fuentes externas y no nos responsabilizamos por errores u omisiones en datos de terceros.",
      },
      section7: {
        title: "7. Cambios en el Aviso Legal",
        p1: "Nos reservamos el derecho de modificar este aviso legal en cualquier momento. Los cambios entran en vigor inmediatamente después de su publicación. El uso continuado de la aplicación después de cambios constituye aceptación de los nuevos términos.",
      },
      section8: {
        title: "8. Ley Aplicable",
        p1: "Este aviso legal se rige por las leyes aplicables de la jurisdicción donde reside el creador, sin considerar conflictos de disposiciones legales.",
      },
      contact: {
        title: "¿Preguntas sobre este Aviso Legal?",
        text: "Si tiene preguntas sobre este aviso legal, póngase en contacto a través de los canales oficiales de la aplicación.",
      },
    },
  },
  en: {
    // Navbar
    nav: {
      dashboard: "Dashboard",
      forecast: "Forecast",
      history: "History",
      replay: "Replay",
      contacts: "Contacts",
    },
    // Header
    header: {
      title: "Hail Storm Monitor",
      subtitle: "Real-time monitoring of severe weather events",
    },
    // Database
    database: {
      title: "Complete Historical Database",
      badge: "10+ Years",
      description:
        "Access over a decade of historical hail data with detailed maps and analysis",
      years: "10+ years of data",
      countries: "50+ countries",
      realtime: "Real-time updates",
    },
    // Alert
    alert: {
      title: "Active Severe Storm Alert",
      description:
        "Multiple areas under severe hail warning. Active monitoring in 12 regions.",
    },
    // Cards
    cards: {
      temperature: "Temperature",
      precipitation: "Precipitation",
      windSpeed: "Wind Speed",
      humidity: "Humidity",
    },
    // Monitoring
    monitoring: {
      title: "Monitoring Areas",
      areas: "monitored areas",
      inUS: "in the United States",
      filter: "Filter by country",
      allCountries: "All Countries",
      highRisk: "High Risk",
      mediumRisk: "Medium Risk",
      lowRisk: "Low Risk",
      updatedAgo: "Updated",
      hailProbability: "Hail Probability",
      expectedSize: "Expected Size",
      temp: "Temp",
      wind: "Wind",
      noAreas: "No areas found for this filter",
    },
    // Charts
    charts: {
      temperature24h: "Temperature (24h)",
      forecastToday: "Today's forecast",
      precipitation7d: "Precipitation (7 days)",
      weeklyHistory: "Weekly history",
    },
    // Activity
    activity: {
      title: "Recent Activity",
      events: {
        severeHail: "Severe hail detected",
        tornadoAlert: "Tornado alert issued",
        severeStorm: "Severe storm in progress",
        favorableConditions: "Favorable conditions for hail",
        monitoringStarted: "Monitoring started",
      },
    },
    // Time
    time: {
      minutesAgo: "{0} minutes ago",
    },
    // Forecast
    forecast: {
      title: "Hail Forecast - Next 12 Months",
      subtitle: "Predictive maps and risk analysis for the next 12 months",
      highRisk: "High Risk",
      mediumRisk: "Medium Risk",
      lowRisk: "Low Risk",
      predictedEvents: "predicted events",
      events: "events",
      riskDescription:
        "High activity period predicted with multiple severe events",
      peakDays: "Peak Days",
      avgEvents: "Average Events",
      perMonth: "per month",
      affectedRegions: "Affected Regions",
      mainRegions: "main regions",
      peakDaysCount: "Peak Days",
      highRiskDays: "high risk days",
      riskLevel: "Risk Level",
      forMonth: "for the month",
    },
    // History
    history: {
      title: "Hail History - 10+ Years",
      subtitle: "Complete database with over a decade of events",
      allRegions: "All Regions",
      searchPlaceholder: "Search by location, date or event...",
      export: "Export",
      totalEvents: "Total Events",
      severe: "severe",
      affectedStates: "Affected States",
      acrossUS: "across US",
      totalDamage: "Total Damage",
      estimated: "estimated",
      peakMonth: "Peak Month",
      mostActive: "most active",
      avgHailSize: "Average Size",
      diameter: "diameter",
      dataPoints: "Data Points",
      collected: "collected",
      notableEvents: "Notable Events",
      hailSize: "Hail Size",
      estimatedDamage: "estimated damage",
    },
    // Replay
    replay: {
      title: "Hail Replay™ - Radar Playback",
      subtitle: "Relive historical events with high-definition radar imagery",
      selectEvent: "Select Event",
      radarView: "Radar View",
      timestamp: "Timestamp",
      maxHailSize: "Max Hail Size",
      speed: "Speed",
      eventDetails: "Event Details",
      date: "Date",
      timeRange: "Time Range",
      location: "Location",
      severity: "Severity",
      statistics: "Statistics",
      duration: "Duration",
      frames: "Frames",
      maxHail: "Max Hail",
      damage: "Damage",
      download: "Download Replay",
      share: "Share",
    },
    // Contacts
    contacts: {
      title: "Unlimited Contact Data",
      subtitle: "On-demand access to thousands of qualified contacts",
      addNew: "Add New",
      import: "Import",
      totalContacts: "Total Contacts",
      unlimited: "unlimited",
      companies: "Companies",
      business: "business",
      locations: "Locations",
      states: "states",
      categories: "Categories",
      types: "types",
      searchPlaceholder: "Search by name, email or phone...",
      export: "Export List",
      name: "Name",
      contact: "Contact",
      location: "Location",
      category: "Category",
      lastContact: "Last Contact",
      noResults: "No contacts found",
      allCategories: "All Categories",
      homeowners: "Homeowners",
      contractors: "Contractors",
      insurance: "Insurance",
      roofing: "Roofing",
      restoration: "Restoration",
    },
    // Months
    months: {
      january: "January",
      february: "February",
      march: "March",
      april: "April",
      may: "May",
      june: "June",
      july: "July",
      august: "August",
      september: "September",
      october: "October",
      november: "November",
      december: "December",
    },
    // Disclaimer
    disclaimer: {
      title: "Legal Notice and Disclaimer",
      lastUpdated: "Last updated: January 2025",
      backToHome: "Back to Home",
      importantNotice: "Important Notice",
      importantText: "Please read this legal notice carefully before using Hai Watch. By accessing and using this application, you agree to the terms and conditions set forth herein.",
      section1: {
        title: "1. General Disclaimer",
        p1: "Hai Watch is a weather monitoring tool provided 'as is' and 'as available'. The information presented in this application is for informational and educational purposes only.",
        p2: "This application does NOT replace official weather alerts issued by competent government authorities (such as NOAA, NWS, or local equivalents).",
        p3: "The creator and developer of this application are not responsible for any decisions made based on the information provided.",
      },
      section2: {
        title: "2. Data Accuracy",
        p1: "While we strive to provide accurate and up-to-date information, we do not guarantee the accuracy, completeness, reliability, or suitability of the weather information presented.",
        p2: "Data may contain errors, inaccuracies, or be outdated. Weather conditions can change rapidly and without notice.",
      },
      section3: {
        title: "3. Limitation of Liability",
        p1: "Under no circumstances shall the creator, developer, or any affiliated party be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from the use or inability to use this application.",
        p2: "This includes, but is not limited to: property damage, financial losses, personal injury, data loss, or loss of profits.",
      },
      section4: {
        title: "4. User Responsibilities",
        intro: "By using Hai Watch, you agree to:",
        item1: "Always consult official meteorological sources for critical safety decisions",
        item2: "Not rely exclusively on this application for life or property protection",
        item3: "Verify information with multiple reliable sources",
        item4: "Follow all safety guidelines issued by local authorities",
      },
      section5: {
        title: "5. Does Not Constitute Professional Advice",
        p1: "The information provided does not constitute professional meteorological, legal, financial, or any other type of advice. For important decisions, consult qualified professionals.",
      },
      section6: {
        title: "6. Third-Party Data",
        p1: "This application may use data from third-party sources. We do not control or guarantee the accuracy of these external sources and are not responsible for errors or omissions in third-party data.",
      },
      section7: {
        title: "7. Changes to Legal Notice",
        p1: "We reserve the right to modify this legal notice at any time. Changes take effect immediately upon publication. Continued use of the application after changes constitutes acceptance of the new terms.",
      },
      section8: {
        title: "8. Governing Law",
        p1: "This legal notice is governed by the applicable laws of the jurisdiction where the creator resides, without regard to conflicts of legal provisions.",
      },
      contact: {
        title: "Questions about this Legal Notice?",
        text: "If you have questions about this legal notice, please contact us through the application's official channels.",
      },
    },
  },
  fr: {
    nav: {
      dashboard: "Tableau de bord",
      forecast: "Prévisions",
      history: "Historique",
      replay: "Relecture",
      contacts: "Contacts",
    },
    header: {
      title: "Moniteur de Tempêtes de Grêle",
      subtitle: "Surveillance en temps réel des événements météorologiques sévères",
    },
    database: {
      title: "Base de Données Historique Complète",
      badge: "10+ Ans",
      description: "Accédez à plus d'une décennie de données historiques sur la grêle",
      years: "10+ années de données",
      countries: "50+ pays",
      realtime: "Mises à jour en temps réel",
    },
    alert: {
      title: "Alerte de Tempête Sévère Active",
      description: "Plusieurs zones sous alerte de grêle sévère",
    },
    cards: {
      temperature: "Température",
      precipitation: "Précipitation",
      windSpeed: "Vitesse du Vent",
      humidity: "Humidité",
    },
    monitoring: {
      title: "Zones de Surveillance",
      areas: "zones surveillées",
      inUS: "aux États-Unis",
      filter: "Filtrer par pays",
      allCountries: "Tous les Pays",
      highRisk: "Risque Élevé",
      mediumRisk: "Risque Moyen",
      lowRisk: "Faible Risque",
      updatedAgo: "Mis à jour il y a",
      hailProbability: "Probabilité de Grêle",
      expectedSize: "Taille Attendue",
      temp: "Temp",
      wind: "Vent",
      noAreas: "Aucune zone trouvée",
    },
    charts: {
      temperature24h: "Température (24h)",
      forecastToday: "Prévisions du jour",
      precipitation7d: "Précipitation (7 jours)",
      weeklyHistory: "Historique hebdomadaire",
    },
    activity: {
      title: "Activité Récente",
      events: {
        severeHail: "Grêle sévère détectée",
        tornadoAlert: "Alerte tornade émise",
        severeStorm: "Tempête sévère en cours",
        favorableConditions: "Conditions favorables",
        monitoringStarted: "Surveillance commencée",
      },
    },
    time: {
      minutesAgo: "il y a {0} minutes",
    },
    forecast: {
      title: "Prévisions de Grêle - 12 Prochains Mois",
      subtitle: "Cartes prédictives et analyse des risques",
      highRisk: "Risque Élevé",
      mediumRisk: "Risque Moyen",
      lowRisk: "Faible Risque",
      predictedEvents: "événements prévus",
      events: "événements",
      riskDescription: "Période de haute activité prévue",
      peakDays: "Jours de Pointe",
      avgEvents: "Événements Moyens",
      perMonth: "par mois",
      affectedRegions: "Régions Affectées",
      mainRegions: "régions principales",
      peakDaysCount: "Jours de Pointe",
      highRiskDays: "jours à haut risque",
      riskLevel: "Niveau de Risque",
      forMonth: "pour le mois",
    },
    history: {
      title: "Historique de Grêle - 10+ Ans",
      subtitle: "Base de données complète",
      allRegions: "Toutes les Régions",
      searchPlaceholder: "Rechercher...",
      export: "Exporter",
      totalEvents: "Total d'Événements",
      severe: "sévères",
      affectedStates: "États Affectés",
      acrossUS: "aux États-Unis",
      totalDamage: "Dommages Totaux",
      estimated: "estimé",
      peakMonth: "Mois de Pointe",
      mostActive: "plus actif",
      avgHailSize: "Taille Moyenne",
      diameter: "diamètre",
      dataPoints: "Points de Données",
      collected: "collectés",
      notableEvents: "Événements Notables",
      hailSize: "Taille de Grêle",
      estimatedDamage: "dommages estimés",
    },
    replay: {
      title: "Hail Replay™ - Relecture Radar",
      subtitle: "Revivez les événements historiques",
      selectEvent: "Sélectionner Événement",
      radarView: "Vue Radar",
      timestamp: "Horodatage",
      maxHailSize: "Taille Max Grêle",
      speed: "Vitesse",
      eventDetails: "Détails de l'Événement",
      date: "Date",
      timeRange: "Plage Horaire",
      location: "Emplacement",
      severity: "Sévérité",
      statistics: "Statistiques",
      duration: "Durée",
      frames: "Images",
      maxHail: "Grêle Max",
      damage: "Dommages",
      download: "Télécharger",
      share: "Partager",
    },
    contacts: {
      title: "Données de Contact Illimitées",
      subtitle: "Accès à la demande",
      addNew: "Ajouter Nouveau",
      import: "Importer",
      totalContacts: "Total Contacts",
      unlimited: "illimité",
      companies: "Entreprises",
      business: "professionnels",
      locations: "Emplacements",
      states: "états",
      categories: "Catégories",
      types: "types",
      searchPlaceholder: "Rechercher...",
      export: "Exporter Liste",
      name: "Nom",
      contact: "Contact",
      location: "Emplacement",
      category: "Catégorie",
      lastContact: "Dernier Contact",
      noResults: "Aucun contact trouvé",
      allCategories: "Toutes Catégories",
      homeowners: "Propriétaires",
      contractors: "Entrepreneurs",
      insurance: "Assurances",
      roofing: "Toiture",
      restoration: "Restauration",
    },
    months: {
      january: "Janvier",
      february: "Février",
      march: "Mars",
      april: "Avril",
      may: "Mai",
      june: "Juin",
      july: "Juillet",
      august: "Août",
      september: "Septembre",
      october: "Octobre",
      november: "Novembre",
      december: "Décembre",
    },
  },
  it: {
    nav: {
      dashboard: "Cruscotto",
      forecast: "Previsioni",
      history: "Storico",
      replay: "Replay",
      contacts: "Contatti",
    },
    header: {
      title: "Monitor Tempeste di Grandine",
      subtitle: "Monitoraggio in tempo reale di eventi meteorologici severi",
    },
    database: {
      title: "Database Storico Completo",
      badge: "10+ Anni",
      description: "Accedi a oltre un decennio di dati storici sulla grandine",
      years: "10+ anni di dati",
      countries: "50+ paesi",
      realtime: "Aggiornamenti in tempo reale",
    },
    alert: {
      title: "Allerta Tempesta Severa Attiva",
      description: "Più aree sotto allerta grandine severa",
    },
    cards: {
      temperature: "Temperatura",
      precipitation: "Precipitazione",
      windSpeed: "Velocità Vento",
      humidity: "Umidità",
    },
    monitoring: {
      title: "Aree di Monitoraggio",
      areas: "aree monitorate",
      inUS: "negli Stati Uniti",
      filter: "Filtra per paese",
      allCountries: "Tutti i Paesi",
      highRisk: "Alto Rischio",
      mediumRisk: "Rischio Medio",
      lowRisk: "Basso Rischio",
      updatedAgo: "Aggiornato",
      hailProbability: "Probabilità Grandine",
      expectedSize: "Dimensione Prevista",
      temp: "Temp",
      wind: "Vento",
      noAreas: "Nessuna area trovata",
    },
    charts: {
      temperature24h: "Temperatura (24h)",
      forecastToday: "Previsioni oggi",
      precipitation7d: "Precipitazione (7 giorni)",
      weeklyHistory: "Storico settimanale",
    },
    activity: {
      title: "Attività Recente",
      events: {
        severeHail: "Grandine severa rilevata",
        tornadoAlert: "Allerta tornado emessa",
        severeStorm: "Tempesta severa in corso",
        favorableConditions: "Condizioni favorevoli",
        monitoringStarted: "Monitoraggio iniziato",
      },
    },
    time: {
      minutesAgo: "{0} minuti fa",
    },
    forecast: {
      title: "Previsioni Grandine - Prossimi 12 Mesi",
      subtitle: "Mappe predittive e analisi del rischio",
      highRisk: "Alto Rischio",
      mediumRisk: "Rischio Medio",
      lowRisk: "Basso Rischio",
      predictedEvents: "eventi previsti",
      events: "eventi",
      riskDescription: "Periodo di alta attività previsto",
      peakDays: "Giorni di Picco",
      avgEvents: "Eventi Medi",
      perMonth: "al mese",
      affectedRegions: "Regioni Colpite",
      mainRegions: "regioni principali",
      peakDaysCount: "Giorni di Picco",
      highRiskDays: "giorni ad alto rischio",
      riskLevel: "Livello di Rischio",
      forMonth: "per il mese",
    },
    history: {
      title: "Storico Grandine - 10+ Anni",
      subtitle: "Database completo",
      allRegions: "Tutte le Regioni",
      searchPlaceholder: "Cerca...",
      export: "Esporta",
      totalEvents: "Eventi Totali",
      severe: "severi",
      affectedStates: "Stati Colpiti",
      acrossUS: "negli USA",
      totalDamage: "Danni Totali",
      estimated: "stimato",
      peakMonth: "Mese di Picco",
      mostActive: "più attivo",
      avgHailSize: "Dimensione Media",
      diameter: "diametro",
      dataPoints: "Punti Dati",
      collected: "raccolti",
      notableEvents: "Eventi Notevoli",
      hailSize: "Dimensione Grandine",
      estimatedDamage: "danni stimati",
    },
    replay: {
      title: "Hail Replay™ - Riproduzione Radar",
      subtitle: "Rivivi eventi storici",
      selectEvent: "Seleziona Evento",
      radarView: "Vista Radar",
      timestamp: "Timestamp",
      maxHailSize: "Dimensione Max Grandine",
      speed: "Velocità",
      eventDetails: "Dettagli Evento",
      date: "Data",
      timeRange: "Intervallo Orario",
      location: "Posizione",
      severity: "Severità",
      statistics: "Statistiche",
      duration: "Durata",
      frames: "Frame",
      maxHail: "Grandine Max",
      damage: "Danni",
      download: "Scarica",
      share: "Condividi",
    },
    contacts: {
      title: "Dati Contatto Illimitati",
      subtitle: "Accesso su richiesta",
      addNew: "Aggiungi Nuovo",
      import: "Importa",
      totalContacts: "Contatti Totali",
      unlimited: "illimitato",
      companies: "Aziende",
      business: "aziendali",
      locations: "Posizioni",
      states: "stati",
      categories: "Categorie",
      types: "tipi",
      searchPlaceholder: "Cerca...",
      export: "Esporta Lista",
      name: "Nome",
      contact: "Contatto",
      location: "Posizione",
      category: "Categoria",
      lastContact: "Ultimo Contatto",
      noResults: "Nessun contatto trovato",
      allCategories: "Tutte Categorie",
      homeowners: "Proprietari",
      contractors: "Appaltatori",
      insurance: "Assicurazioni",
      roofing: "Coperture",
      restoration: "Restauro",
    },
    months: {
      january: "Gennaio",
      february: "Febbraio",
      march: "Marzo",
      april: "Aprile",
      may: "Maggio",
      june: "Giugno",
      july: "Luglio",
      august: "Agosto",
      september: "Settembre",
      october: "Ottobre",
      november: "Novembre",
      december: "Dicembre",
    },
  },
  ja: {
    nav: {
      dashboard: "ダッシュボード",
      forecast: "予報",
      history: "履歴",
      replay: "リプレイ",
      contacts: "連絡先",
    },
    header: {
      title: "雹嵐モニター",
      subtitle: "悪天候イベントのリアルタイム監視",
    },
    database: {
      title: "完全な歴史データベース",
      badge: "10年以上",
      description: "10年以上の雹の歴史データにアクセス",
      years: "10年以上のデータ",
      countries: "50か国以上",
      realtime: "リアルタイム更新",
    },
    alert: {
      title: "激しい嵐警報発令中",
      description: "複数の地域で激しい雹警報",
    },
    cards: {
      temperature: "気温",
      precipitation: "降水量",
      windSpeed: "風速",
      humidity: "湿度",
    },
    monitoring: {
      title: "監視エリア",
      areas: "監視エリア",
      inUS: "米国内",
      filter: "国でフィルター",
      allCountries: "すべての国",
      highRisk: "高リスク",
      mediumRisk: "中リスク",
      lowRisk: "低リスク",
      updatedAgo: "更新",
      hailProbability: "雹の確率",
      expectedSize: "予想サイズ",
      temp: "気温",
      wind: "風",
      noAreas: "エリアが見つかりません",
    },
    charts: {
      temperature24h: "気温（24時間）",
      forecastToday: "今日の予報",
      precipitation7d: "降水量（7日間）",
      weeklyHistory: "週間履歴",
    },
    activity: {
      title: "最近のアクティビティ",
      events: {
        severeHail: "激しい雹を検出",
        tornadoAlert: "竜巻警報発令",
        severeStorm: "激しい嵐進行中",
        favorableConditions: "好条件",
        monitoringStarted: "監視開始",
      },
    },
    time: {
      minutesAgo: "{0}分前",
    },
    forecast: {
      title: "雹予報 - 今後12か月",
      subtitle: "予測マップとリスク分析",
      highRisk: "高リスク",
      mediumRisk: "中リスク",
      lowRisk: "低リスク",
      predictedEvents: "予測イベント",
      events: "イベント",
      riskDescription: "高活動期間予測",
      peakDays: "ピーク日",
      avgEvents: "平均イベント",
      perMonth: "月あたり",
      affectedRegions: "影響地域",
      mainRegions: "主要地域",
      peakDaysCount: "ピーク日",
      highRiskDays: "高リスク日",
      riskLevel: "リスクレベル",
      forMonth: "月間",
    },
    history: {
      title: "雹履歴 - 10年以上",
      subtitle: "完全なデータベース",
      allRegions: "すべての地域",
      searchPlaceholder: "検索...",
      export: "エクスポート",
      totalEvents: "総イベント数",
      severe: "激しい",
      affectedStates: "影響を受けた州",
      acrossUS: "米国全体",
      totalDamage: "総被害額",
      estimated: "推定",
      peakMonth: "ピーク月",
      mostActive: "最も活発",
      avgHailSize: "平均サイズ",
      diameter: "直径",
      dataPoints: "データポイント",
      collected: "収集済み",
      notableEvents: "注目イベント",
      hailSize: "雹のサイズ",
      estimatedDamage: "推定被害",
    },
    replay: {
      title: "Hail Replay™ - レーダー再生",
      subtitle: "歴史的イベントを再体験",
      selectEvent: "イベント選択",
      radarView: "レーダービュー",
      timestamp: "タイムスタンプ",
      maxHailSize: "最大雹サイズ",
      speed: "速度",
      eventDetails: "イベント詳細",
      date: "日付",
      timeRange: "時間範囲",
      location: "場所",
      severity: "深刻度",
      statistics: "統計",
      duration: "期間",
      frames: "フレーム",
      maxHail: "最大雹",
      damage: "被害",
      download: "ダウンロード",
      share: "共有",
    },
    contacts: {
      title: "無制限の連絡先データ",
      subtitle: "オンデマンドアクセス",
      addNew: "新規追加",
      import: "インポート",
      totalContacts: "総連絡先数",
      unlimited: "無制限",
      companies: "企業",
      business: "ビジネス",
      locations: "場所",
      states: "州",
      categories: "カテゴリ",
      types: "タイプ",
      searchPlaceholder: "検索...",
      export: "リストをエクスポート",
      name: "名前",
      contact: "連絡先",
      location: "場所",
      category: "カテゴリ",
      lastContact: "最終連絡",
      noResults: "連絡先が見つかりません",
      allCategories: "すべてのカテゴリ",
      homeowners: "住宅所有者",
      contractors: "請負業者",
      insurance: "保険",
      roofing: "屋根",
      restoration: "修復",
    },
    months: {
      january: "1月",
      february: "2月",
      march: "3月",
      april: "4月",
      may: "5月",
      june: "6月",
      july: "7月",
      august: "8月",
      september: "9月",
      october: "10月",
      november: "11月",
      december: "12月",
    },
  },
  ru: {
    nav: {
      dashboard: "Панель",
      forecast: "Прогноз",
      history: "История",
      replay: "Повтор",
      contacts: "Контакты",
    },
    header: {
      title: "Монитор Градовых Бурь",
      subtitle: "Мониторинг суровых погодных явлений в реальном времени",
    },
    database: {
      title: "Полная Историческая База Данных",
      badge: "10+ Лет",
      description: "Доступ к более чем десятилетию исторических данных о граде",
      years: "10+ лет данных",
      countries: "50+ стран",
      realtime: "Обновления в реальном времени",
    },
    alert: {
      title: "Активное Предупреждение о Суровой Буре",
      description: "Несколько районов под предупреждением о сильном граде",
    },
    cards: {
      temperature: "Температура",
      precipitation: "Осадки",
      windSpeed: "Скорость Ветра",
      humidity: "Влажность",
    },
    monitoring: {
      title: "Зоны Мониторинга",
      areas: "контролируемых зон",
      inUS: "в США",
      filter: "Фильтр по стране",
      allCountries: "Все Страны",
      highRisk: "Высокий Риск",
      mediumRisk: "Средний Риск",
      lowRisk: "Низкий Риск",
      updatedAgo: "Обновлено",
      hailProbability: "Вероятность Града",
      expectedSize: "Ожидаемый Размер",
      temp: "Темп",
      wind: "Ветер",
      noAreas: "Зоны не найдены",
    },
    charts: {
      temperature24h: "Температура (24ч)",
      forecastToday: "Прогноз на сегодня",
      precipitation7d: "Осадки (7 дней)",
      weeklyHistory: "Недельная история",
    },
    activity: {
      title: "Недавняя Активность",
      events: {
        severeHail: "Обнаружен сильный град",
        tornadoAlert: "Выпущено предупреждение о торнадо",
        severeStorm: "Сильная буря в процессе",
        favorableConditions: "Благоприятные условия",
        monitoringStarted: "Мониторинг начат",
      },
    },
    time: {
      minutesAgo: "{0} минут назад",
    },
    forecast: {
      title: "Прогноз Града - Следующие 12 Месяцев",
      subtitle: "Прогнозные карты и анализ рисков",
      highRisk: "Высокий Риск",
      mediumRisk: "Средний Риск",
      lowRisk: "Низкий Риск",
      predictedEvents: "прогнозируемых событий",
      events: "события",
      riskDescription: "Прогнозируется период высокой активности",
      peakDays: "Пиковые Дни",
      avgEvents: "Средние События",
      perMonth: "в месяц",
      affectedRegions: "Затронутые Регионы",
      mainRegions: "основных регионов",
      peakDaysCount: "Пиковые Дни",
      highRiskDays: "дней высокого риска",
      riskLevel: "Уровень Риска",
      forMonth: "за месяц",
    },
    history: {
      title: "История Града - 10+ Лет",
      subtitle: "Полная база данных",
      allRegions: "Все Регионы",
      searchPlaceholder: "Поиск...",
      export: "Экспорт",
      totalEvents: "Всего Событий",
      severe: "суровых",
      affectedStates: "Затронутые Штаты",
      acrossUS: "по США",
      totalDamage: "Общий Ущерб",
      estimated: "оценочный",
      peakMonth: "Пиковый Месяц",
      mostActive: "наиболее активный",
      avgHailSize: "Средний Размер",
      diameter: "диаметр",
      dataPoints: "Точки Данных",
      collected: "собрано",
      notableEvents: "Заметные События",
      hailSize: "Размер Града",
      estimatedDamage: "оценочный ущерб",
    },
    replay: {
      title: "Hail Replay™ - Воспроизведение Радара",
      subtitle: "Переживите исторические события",
      selectEvent: "Выбрать Событие",
      radarView: "Вид Радара",
      timestamp: "Временная Метка",
      maxHailSize: "Макс Размер Града",
      speed: "Скорость",
      eventDetails: "Детали События",
      date: "Дата",
      timeRange: "Временной Диапазон",
      location: "Местоположение",
      severity: "Серьезность",
      statistics: "Статистика",
      duration: "Продолжительность",
      frames: "Кадры",
      maxHail: "Макс Град",
      damage: "Ущерб",
      download: "Скачать",
      share: "Поделиться",
    },
    contacts: {
      title: "Неограниченные Контактные Данные",
      subtitle: "Доступ по требованию",
      addNew: "Добавить Новый",
      import: "Импорт",
      totalContacts: "Всего Контактов",
      unlimited: "неограниченно",
      companies: "Компании",
      business: "бизнес",
      locations: "Местоположения",
      states: "штаты",
      categories: "Категории",
      types: "типы",
      searchPlaceholder: "Поиск...",
      export: "Экспорт Списка",
      name: "Имя",
      contact: "Контакт",
      location: "Местоположение",
      category: "Категория",
      lastContact: "Последний Контакт",
      noResults: "Контакты не найдены",
      allCategories: "Все Категории",
      homeowners: "Домовладельцы",
      contractors: "Подрядчики",
      insurance: "Страхование",
      roofing: "Кровля",
      restoration: "Восстановление",
    },
    months: {
      january: "Январь",
      february: "Февраль",
      march: "Март",
      april: "Апрель",
      may: "Май",
      june: "Июнь",
      july: "Июль",
      august: "Август",
      september: "Сентябрь",
      october: "Октябрь",
      november: "Ноябрь",
      december: "Декабрь",
    },
  },
  de: {
    nav: {
      dashboard: "Dashboard",
      forecast: "Vorhersage",
      history: "Verlauf",
      replay: "Wiedergabe",
      contacts: "Kontakte",
    },
    header: {
      title: "Hagelsturm-Monitor",
      subtitle: "Echtzeitüberwachung schwerer Wetterereignisse",
    },
    database: {
      title: "Vollständige Historische Datenbank",
      badge: "10+ Jahre",
      description: "Zugriff auf über ein Jahrzehnt historischer Hageldaten",
      years: "10+ Jahre Daten",
      countries: "50+ Länder",
      realtime: "Echtzeit-Updates",
    },
    alert: {
      title: "Aktive Schwere Sturmwarnung",
      description: "Mehrere Gebiete unter schwerer Hagelwarnung",
    },
    cards: {
      temperature: "Temperatur",
      precipitation: "Niederschlag",
      windSpeed: "Windgeschwindigkeit",
      humidity: "Luftfeuchtigkeit",
    },
    monitoring: {
      title: "Überwachungsbereiche",
      areas: "überwachte Bereiche",
      inUS: "in den USA",
      filter: "Nach Land filtern",
      allCountries: "Alle Länder",
      highRisk: "Hohes Risiko",
      mediumRisk: "Mittleres Risiko",
      lowRisk: "Geringes Risiko",
      updatedAgo: "Aktualisiert",
      hailProbability: "Hagelwahrscheinlichkeit",
      expectedSize: "Erwartete Größe",
      temp: "Temp",
      wind: "Wind",
      noAreas: "Keine Bereiche gefunden",
    },
    charts: {
      temperature24h: "Temperatur (24h)",
      forecastToday: "Vorhersage heute",
      precipitation7d: "Niederschlag (7 Tage)",
      weeklyHistory: "Wöchentlicher Verlauf",
    },
    activity: {
      title: "Letzte Aktivität",
      events: {
        severeHail: "Schwerer Hagel erkannt",
        tornadoAlert: "Tornado-Warnung ausgegeben",
        severeStorm: "Schwerer Sturm im Gange",
        favorableConditions: "Günstige Bedingungen",
        monitoringStarted: "Überwachung gestartet",
      },
    },
    time: {
      minutesAgo: "vor {0} Minuten",
    },
    forecast: {
      title: "Hagelvorhersage - Nächste 12 Monate",
      subtitle: "Vorhersagekarten und Risikoanalyse",
      highRisk: "Hohes Risiko",
      mediumRisk: "Mittleres Risiko",
      lowRisk: "Geringes Risiko",
      predictedEvents: "vorhergesagte Ereignisse",
      events: "Ereignisse",
      riskDescription: "Periode hoher Aktivität vorhergesagt",
      peakDays: "Spitzentage",
      avgEvents: "Durchschnittliche Ereignisse",
      perMonth: "pro Monat",
      affectedRegions: "Betroffene Regionen",
      mainRegions: "Hauptregionen",
      peakDaysCount: "Spitzentage",
      highRiskDays: "Tage mit hohem Risiko",
      riskLevel: "Risikoniveau",
      forMonth: "für den Monat",
    },
    history: {
      title: "Hagelverlauf - 10+ Jahre",
      subtitle: "Vollständige Datenbank",
      allRegions: "Alle Regionen",
      searchPlaceholder: "Suchen...",
      export: "Exportieren",
      totalEvents: "Gesamtereignisse",
      severe: "schwer",
      affectedStates: "Betroffene Staaten",
      acrossUS: "in den USA",
      totalDamage: "Gesamtschaden",
      estimated: "geschätzt",
      peakMonth: "Spitzenmonat",
      mostActive: "am aktivsten",
      avgHailSize: "Durchschnittsgröße",
      diameter: "Durchmesser",
      dataPoints: "Datenpunkte",
      collected: "gesammelt",
      notableEvents: "Bemerkenswerte Ereignisse",
      hailSize: "Hagelgröße",
      estimatedDamage: "geschätzter Schaden",
    },
    replay: {
      title: "Hail Replay™ - Radar-Wiedergabe",
      subtitle: "Erleben Sie historische Ereignisse",
      selectEvent: "Ereignis Auswählen",
      radarView: "Radaransicht",
      timestamp: "Zeitstempel",
      maxHailSize: "Max Hagelgröße",
      speed: "Geschwindigkeit",
      eventDetails: "Ereignisdetails",
      date: "Datum",
      timeRange: "Zeitbereich",
      location: "Standort",
      severity: "Schweregrad",
      statistics: "Statistiken",
      duration: "Dauer",
      frames: "Frames",
      maxHail: "Max Hagel",
      damage: "Schaden",
      download: "Herunterladen",
      share: "Teilen",
    },
    contacts: {
      title: "Unbegrenzte Kontaktdaten",
      subtitle: "Zugriff auf Abruf",
      addNew: "Neu Hinzufügen",
      import: "Importieren",
      totalContacts: "Gesamtkontakte",
      unlimited: "unbegrenzt",
      companies: "Unternehmen",
      business: "geschäftlich",
      locations: "Standorte",
      states: "Staaten",
      categories: "Kategorien",
      types: "Typen",
      searchPlaceholder: "Suchen...",
      export: "Liste Exportieren",
      name: "Name",
      contact: "Kontakt",
      location: "Standort",
      category: "Kategorie",
      lastContact: "Letzter Kontakt",
      noResults: "Keine Kontakte gefunden",
      allCategories: "Alle Kategorien",
      homeowners: "Hausbesitzer",
      contractors: "Auftragnehmer",
      insurance: "Versicherung",
      roofing: "Bedachung",
      restoration: "Wiederherstellung",
    },
    months: {
      january: "Januar",
      february: "Februar",
      march: "März",
      april: "April",
      may: "Mai",
      june: "Juni",
      july: "Juli",
      august: "August",
      september: "September",
      october: "Oktober",
      november: "November",
      december: "Dezember",
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === "object") {
        value = value[k];
      } else {
        return key;
      }
    }

    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
